"""The corpus manifest and its lockfile.

The PDFs themselves are never committed -- they are third-party documents of
varying licence, and some are large. What *is* committed is this pair of files:

* ``configs/corpus.yaml``      -- hand-authored. URLs, licences, why each
  document is in the corpus. Comments and structure matter here, so nothing
  ever machine-rewrites it.
* ``configs/corpus.lock.yaml`` -- generated by ``mmrag corpus lock``. The
  SHA-256, byte size, and page count each file must have.

Splitting them is the same reasoning as ``package.json`` vs ``package-lock.json``:
intent stays readable and reviewable, integrity stays exact and machine-managed.
Together they are what makes the benchmark reproducible -- anyone cloning the
repo provably ends up with byte-identical inputs, so a difference in their
numbers comes from the pipeline and not from a silently re-issued PDF.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, Field, field_validator

from mmrag.config import CONFIG_DIR, RAW_DIR

DEFAULT_MANIFEST_PATH = CONFIG_DIR / "corpus.yaml"
DEFAULT_LOCK_PATH = CONFIG_DIR / "corpus.lock.yaml"

# What a document is expected to stress. Used to slice evaluation results by
# document character ("did Method 3 only win on the chart-heavy documents?").
ModalityTag = Literal[
    "dense_text",
    "tables",
    "charts",
    "diagrams",
    "photos",
    "equations",
    "multi_column",
    "scanned",
]


def _valid_sha256(v: str | None) -> str | None:
    if v is None:
        return None
    v = v.strip().lower()
    if len(v) != 64 or any(c not in "0123456789abcdef" for c in v):
        raise ValueError(f"sha256 must be 64 hex characters, got {v!r}")
    return v


# ---------------------------------------------------------------------------
# Manifest (hand-authored)
# ---------------------------------------------------------------------------


class CorpusEntry(BaseModel):
    """One source document, as declared by a human."""

    doc_id: str = Field(pattern=r"^[a-z0-9][a-z0-9_\-]*$")
    title: str
    url: str
    publisher: str | None = None
    category: str | None = None
    license: str | None = None

    modality_profile: list[ModalityTag] = Field(default_factory=list)
    notes: str | None = None
    # Set false to keep an entry documented but out of the active run.
    enabled: bool = True

    # Ingest only the first N pages. Some sources (a 640-page datasheet) would
    # otherwise dominate the corpus and skew every per-document metric, so they
    # are truncated to a representative prefix rather than dropped entirely.
    page_limit: int | None = Field(default=None, ge=1)

    # --- populated from the lockfile, never written back to corpus.yaml ------
    sha256: str | None = Field(default=None, exclude=True)
    size_bytes: int | None = Field(default=None, exclude=True)
    n_pages: int | None = Field(default=None, exclude=True)

    _check_sha = field_validator("sha256")(_valid_sha256)

    @property
    def filename(self) -> str:
        return f"{self.doc_id}.pdf"

    def local_path(self, raw_dir: Path | None = None) -> Path:
        return (raw_dir or RAW_DIR) / self.filename

    @property
    def effective_pages(self) -> int | None:
        """Pages that will actually be ingested, after any ``page_limit``."""
        if self.n_pages is None:
            return None
        return min(self.n_pages, self.page_limit) if self.page_limit else self.n_pages


class CorpusManifest(BaseModel):
    version: int = 1
    description: str = ""
    entries: list[CorpusEntry] = Field(default_factory=list)

    @field_validator("entries")
    @classmethod
    def _unique_ids(cls, v: list[CorpusEntry]) -> list[CorpusEntry]:
        seen: set[str] = set()
        for entry in v:
            if entry.doc_id in seen:
                raise ValueError(f"duplicate doc_id in manifest: {entry.doc_id}")
            seen.add(entry.doc_id)
        return v

    @property
    def active(self) -> list[CorpusEntry]:
        return [e for e in self.entries if e.enabled]

    def get(self, doc_id: str) -> CorpusEntry:
        for entry in self.entries:
            if entry.doc_id == doc_id:
                return entry
        known = ", ".join(e.doc_id for e in self.entries)
        raise KeyError(f"no such doc_id {doc_id!r}. Known ids: {known}")

    @classmethod
    def load(
        cls,
        path: Path | str | None = None,
        *,
        lock_path: Path | str | None = None,
        apply_lock: bool = True,
    ) -> CorpusManifest:
        """Read the manifest and overlay the lockfile's integrity data."""
        p = Path(path) if path else DEFAULT_MANIFEST_PATH
        if not p.exists():
            raise FileNotFoundError(f"corpus manifest not found: {p}")
        with p.open("r", encoding="utf-8") as fh:
            data: dict[str, Any] = yaml.safe_load(fh) or {}
        manifest = cls.model_validate(data)

        if apply_lock:
            lp = Path(lock_path) if lock_path else DEFAULT_LOCK_PATH
            if lp.exists():
                manifest.apply_lock(CorpusLock.load(lp))
        return manifest

    def apply_lock(self, lock: CorpusLock) -> None:
        """Copy pinned integrity data onto the matching entries, in place."""
        for entry in self.entries:
            pin = lock.entries.get(entry.doc_id)
            if pin is None:
                continue
            entry.sha256 = pin.sha256
            entry.size_bytes = pin.size_bytes
            entry.n_pages = pin.n_pages


# ---------------------------------------------------------------------------
# Lockfile (generated)
# ---------------------------------------------------------------------------


class CorpusLockEntry(BaseModel):
    sha256: str
    size_bytes: int
    n_pages: int | None = None

    _check_sha = field_validator("sha256")(_valid_sha256)


class CorpusLock(BaseModel):
    """Generated integrity pins. Committed, but never hand-edited."""

    version: int = 1
    generated_at: str = ""
    entries: dict[str, CorpusLockEntry] = Field(default_factory=dict)

    @classmethod
    def load(cls, path: Path | str | None = None) -> CorpusLock:
        p = Path(path) if path else DEFAULT_LOCK_PATH
        if not p.exists():
            raise FileNotFoundError(f"corpus lockfile not found: {p}")
        with p.open("r", encoding="utf-8") as fh:
            return cls.model_validate(yaml.safe_load(fh) or {})

    def save(self, path: Path | str | None = None) -> Path:
        p = Path(path) if path else DEFAULT_LOCK_PATH
        self.generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
        header = (
            "# Generated by `mmrag corpus lock` -- do not edit by hand.\n"
            "# Pins the exact bytes of every corpus document so that every clone of\n"
            "# this repository indexes identical inputs. Edit configs/corpus.yaml\n"
            "# instead, then re-run the lock command.\n"
        )
        # sort_keys keeps the diff stable when a single document is re-pinned.
        body = yaml.safe_dump(
            self.model_dump(mode="json"), sort_keys=True, allow_unicode=True, width=100
        )
        p.write_text(header + body, encoding="utf-8")
        return p
